name: deploy to prod

on:
  release:
    types: [created]

# Copied from staging.yml.
# GitHub does not support sharing steps between workflows yet.
jobs:
  deployment-prod:
    runs-on: ubuntu-latest
    env:
      CI: false

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y make rsync git apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa-bastion
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          config: |
            Host covidcalc
              User root
              Hostname covidcalc.org
              IdentityFile ~/.ssh/id_rsa-bastion
      - name: Install and Build ðŸ”§
        env:
          CI: false
          PUBLIC_URL: /
        run: |
          npm install
          npm run build
          scp -i ~/.ssh/id_rsa-bastion -o StrictHostKeyChecking=no -r build/* root@covidcalc.org:/var/www/html
